[package]
name = "async-utility"
version = "0.1.1"
edition = "2021"
description = "Collection of async utilities."
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
homepage = "https://github.com/yukibtc/async-utility"
repository = "https://github.com/yukibtc/async-utility.git"
license = "MIT"
readme = "README.md"
keywords = ["async", "tokio", "util"]

[features]
default = []
blocking = []

[dependencies]
crossbeam-channel = "0.5"
futures-util = { version = "0.3", default-features = false, features = ["std", "sink"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "rt-multi-thread", "time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.2", features = ["futures"] }
tokio = { version = "1", default-features = false, features = ["rt", "sync"] }
wasm-bindgen-futures = "0.4"
